# SPDX-FileCopyrightText: 2014, 2016 CERN.
# SPDX-License-Identifier: MIT

[pytest]
addopts = --isort --pydocstyle --pycodestyle --doctest-glob="*.rst" --doctest-modules --cov=dictdiffer --cov-report=term-missing
testpaths = tests dictdiffer
filterwarnings = ignore::pytest.PytestDeprecationWarning
